#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on mitaka."""

from basic_deployment import DesignateBindDeployment

if __name__ == '__main__':
    deployment = DesignateBindDeployment(series='xenial')
    deployment.run_tests()
